### DISCUSSION TITLE
Kyoo Unable to Detect Videos in Mounted Volumes Despite Correct Configuration

### DISCUSSION THREAD

**Discussion by djwizzer** [zoriya/Kyoo#630] [Q&A] [answered]
### Kyoo Unable to Detect Videos in Mounted Volumes Despite Correct Configuration

Hello,

I am experiencing an issue where Kyoo is not detecting any videos in my mounted volumes. Here is a summary of the steps I’ve taken so far:

1. I have multiple mounted volumes on my Ubuntu server: `/mnt/1to`, `/mnt/500go`, `/mnt/500go_vm`, and `/mnt/640gofreebox`. These volumes contain various video files that I want Kyoo to scan.
2. I have configured my `docker-compose.yml` file to mount these volumes for both the `transcoder` and `scanner` services:
   ```yaml
   x-transcoder: &transcoder-base
     image: ghcr.io/zoriya/kyoo_transcoder:edge
     networks:
       default:
         aliases:
           - transcoder
     restart: unless-stopped
     env_file:
       - ./.env
     environment:
       - GOCODER_PREFIX=/video
     volumes:
       - /mnt/1to:/video/1:ro
       - /mnt/500go:/video/500go:ro
       - /mnt/500go_vm:/video/500go_vm:ro
       - /mnt/640gofreebox:/video/640gofreebox:ro
       - ${CACHE_ROOT}:/cache
       - metadata:/metadata

   services:
     transcoder:
       <<: *transcoder-base

     scanner:
       image: ghcr.io/zoriya/kyoo_scanner:edge
       restart: unless-stopped
       depends_on:
         back:
           condition: service_healthy
       env_file:
         - ./.env
       environment:
         - KYOO_URL=${KYOO_URL:-http://back:5000}
       volumes:
         - /mnt/1to:/video/1:ro
         - /mnt/500go:/video/500go:ro
         - /mnt/500go_vm:/video/500go_vm:ro
         - /mnt/640gofreebox:/video/640gofreebox:ro
   ```

3. I have ensured that the `.env` file's `LIBRARY_ROOT` variable points to all the volumes:
   ```env
   LIBRARY_ROOT=/mnt/1to,/mnt/500go,/mnt/500go_vm,/mnt/640gofreebox
   ```

4. I have verified the permissions on the directories, and Docker is able to access the files inside them when testing with a separate container. 

5. After restarting the Kyoo services with `docker compose down && docker compose up -d`, no videos are detected, and the message "No video was found yet" appears on the web interface.

I would appreciate any insights or suggestions on what might be causing this issue or if there are any additional troubleshooting steps I should take.

Thank you!
