### ISSUE TITLE
dGPU hardware acceleration not working in systems with an iGPU

### ISSUE THREAD

**Issue by anhminhpho** [zoriya/Kyoo#641]
### Kyoo's version

4.7.0

### What happened?

Bonjour :)

In a system with an integrated GPU, Kyoo doesn't seem to have access to the dedicated GPU for hardware accelerated transcoding. Infinite loading screen, no GPU activity and no ffmpeg process running: 

dGPU
![image](https://github.com/user-attachments/assets/9eb0114a-cf50-493c-a73f-69fbb62739d8)

iGPU
![image](https://github.com/user-attachments/assets/97d03318-1f7e-45e5-a775-e64f6ca0b406)

Modifying the **transcoder-nvidia** block in the docker-compose file according to this [docker documentation](https://docs.docker.com/compose/how-tos/gpu-support/#access-specific-devices) fixes the bug, but I'm not sure if it's the best way to do it in this context.

```yaml
          devices:
            - capabilities: [gpu]
```

```yaml
          devices:
            - driver: nvidia
              device_ids: ['0']
              capabilities: [gpu]
```

Ubuntu Server 22.04
CPU with iGPU: Ryzen 7 5700G
dGPU: Nvidia GTX 1080
