### ISSUE TITLE
QNAP questions

### ISSUE THREAD

**Issue by pintaf** [zoriya/Kyoo#864]
### Kyoo's version

4.7.1

### What happened?

Hi!

I'm trying to do something that might be "unsupported" at first sight, but I'm actually close to succeeding.
I'm trying to deploy Kyoo on a QNAP NAS.

The QNAP has container support, but it seems it does not support .env files (Well... I think it is possible to use them via SSH, but I want to make it all via the web interface to wrap up a tutorial for non-tech people).

So, if .env is not supported, I just need to manually specify env variables in the docker-compose file, which is what I did.
I looked in the code to see in which containers these env variables where used, but I might have missed something and this could be the reason of the issue.

> To know, also, I'm in a constrained environment, 4 core 1,6 Ghz celeron CPU - N3160 (GPU transcoding capable) and 8GB of RAM.
> Other changes I have made in the docker-compose: removing the "transcoder-nvidia" service as I don't have any nvidia card, and increasing the retries for the healthchecks as due to memory constraints, I've seen some containers taking time to start or even failing on first attempt, but succeeding afterwards.

You will find attached the docker-compose logs and the docker-compose.yml file (renamed txt because github don't allow yml)
[docker-compose.txt](https://github.com/user-attachments/files/19523088/docker-compose.txt)
[logs.txt](https://github.com/user-attachments/files/19523104/logs.txt)

I have identified the problematic API call:
Most of Kyoo runs smoothly, it finds the videos, is able to gets the details, account CRUD is working... Only issue is launching the movie.
**Both on web and android, once I click play on a movie, I get a 503 "Service Unavailable" on `/api/movie/{movie-identifier}/info`
When I click the download btn in android, this time it's a 401 that I get for the same call.**

I tried to find the definition of this `/api/movie/{movie-identifier}/info` endpoint in the code. 
I checked the [Movie Api](https://github.com/zoriya/Kyoo/blob/v4.7.1/back/src/Kyoo.Core/Views/Resources/MovieApi.cs) but did not find anything about "info"
I also checked the [Info Api](https://github.com/zoriya/Kyoo/blob/v4.7.1/back/src/Kyoo.Core/Views/InfoApi.cs) but that seems related to OpenIdConnect which I don't use.

If at least you could indicate me where in the code is handled this `/api/movie/{movie-identifier}/info`, I could pursue my investigations. I'm not fluent in C, C#, rust. 😅

**Comment by zoriya** [comment]
The `api/movie/id/info` is defined in the [Transcoder.cs](https://github.com/zoriya/Kyoo/blob/master/back/src/Kyoo.Core/Views/Helper/Transcoder.cs) file. Looking at your docker-compose.yaml file the issue seems to be the `TRANSCODER_URL` specified in the back container. It has an extra `-` at the begining (i.e. `TRANSCODER_URL=-http://transcoder:7666/video` instead of `TRANSCODER_URL=http://transcoder:7666/video`)

**Comment by zoriya** [comment]
Btw i don't really know how the QNAS ecosystem works but if there's anything that can be done to make installing/using kyoo easier there i'm absolutly open to any contributions (in the code or for packaging stuff)

**Comment by pintaf** [comment]
Hi !

Thanks, it was indeed this issue. Hard to spot, congrats !
After that , I was able to play movies in the web, with the cpu transcoder starting. However this quickly put my NAS on it's knees (like beeping and displaying "system failure" 😅), so I'm now focusing on having it working with vaapi HW accell ([it seems to work for jellyfin](https://github.com/pdulvp/jellyfin-qnap?tab=readme-ov-file#-enable-video-acceleration-in-jellyfin-))

While tinkering with all your docker setup, I found out that quite often some docker where failing (mainly RabbitMQ)
They were mainly failing due to some obscure reasons but probably due to resource constraints, because when launching them again, they did boot properly.

In order to avoid that, and at the cost of a longer boot, I decided to reduce that starting concurency by adding more "depends_on".
By matter of principle, I start the DB and the migrations first, then meilisearche and rabbitMQ, then the back, the front, followed by traefik to serve all that. Only after I start matcher, scanner, sync, and transcoder, because they're not needed until the user can actually be in the app.

Maybe it would be a great thing to do the same for the v5 ? The media centers are often resource constrained devices and doing so (stagger the starts) might enable to more broadly deploy kyoo. I also read your V5 roadmap, I find it a good idea to merge some services together, reducing the number of dockers. Every docker has his base image which take some resources, even if it's low.

Ah, I also added a healthcheck on traefik so that other containers can depend on it. You might want to apply in your configuration.

Looking forward the v5 to maybe try packaging an app or something that looks like a one click install. For the moment, if I can end up with a tutorial for v4, it would be nice. 🤞

Thanks for the help again. I'll try to dig into the issues of HW accell and will most probably come back for help.

❕Bellow is my docker-compose for your information

```
services:
  back:
    image: ghcr.io/zoriya/kyoo_back:4.7
    restart: unless-stopped
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_DEFAULT_USER=kyoo
      - RABBITMQ_DEFAULT_PASS=aohohunuhouhuhhoahothonseuhaoensuthoaentsuhha
      - KYOO_APIKEYS=t7Hw5!@4iMNsAasdajkljkaldjsjahsddSJQd49pwat4jprJgTcFd656if#J3
      - REQUIRE_ACCOUNT_VERIFICATION=true
      - TRANSCODER_URL=http://transcoder:7666/video
      - KYOO_PREFIX=/api
      - POSTGRES_USER=KyooUser
      - POSTGRES_PASSWORD=KyooPassword
      - POSTGRES_DB=kyooDB
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_MASTER_KEY=ghvjkgisbgkbgskegblfqbgjkebbhgwkjfb
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - kyoo:/metadata
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=PathPrefix(`/api/`)"

  migrations:
    image: ghcr.io/zoriya/kyoo_migrations:4.7
    restart: "no"
    depends_on:
      postgres:
        condition: service_healthy

  front:
    image: ghcr.io/zoriya/kyoo_front:4.7
    restart: unless-stopped
    environment:
      - KYOO_URL=http://back:5000/api
    depends_on:
      back:
        condition: service_healthy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.front.rule=PathPrefix(`/`)"

  scanner:
    image: ghcr.io/zoriya/kyoo_scanner:4.7
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_DEFAULT_USER=kyoo
      - RABBITMQ_DEFAULT_PASS=aohohunuhouhuhhoahothonseuhaoensuthoaentsuhha
      - KYOO_APIKEYS=t7Hw5!@4iMNsAasdajkljkaldjsjahsddSJQd49pwat4jprJgTcFd656if#J3
      - LIBRARY_LANGUAGES=fr,en
      - KYOO_URL=http://back:5000/api
    volumes:
      - /share/disque12TB/films/to-re-download:/video:ro

  matcher:
    image: ghcr.io/zoriya/kyoo_scanner:4.7
    command: matcher
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_DEFAULT_USER=kyoo
      - RABBITMQ_DEFAULT_PASS=aohohunuhouhuhhoahothonseuhaoensuthoaentsuhha
      - KYOO_APIKEYS=t7Hw5!@4iMNsAasdajkljkaldjsjahsddSJQd49pwat4jprJgTcFd656if#J3
      - LIBRARY_LANGUAGES=fr,en
      - KYOO_URL=http://back:5000/api

  autosync:
    image: ghcr.io/zoriya/kyoo_autosync:4.7
    restart: unless-stopped
    depends_on:
      traefik:
        condition: service_healthy
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_DEFAULT_USER=kyoo
      - RABBITMQ_DEFAULT_PASS=aohohunuhouhuhhoahothonseuhaoensuthoaentsuhha

  transcoder-vaapi:
    image: ghcr.io/zoriya/kyoo_transcoder:4.7
    networks:
      default:
        aliases:
          - transcoder
    restart: unless-stopped
    environment:
      - GOCODER_PREFIX=/video
      - GOCODER_HWACCEL=vaapi
      - GOCODER_VAAPI_RENDERER=/dev/dri/renderD128
      - COMPOSE_PROFILES=vaapi
      - POSTGRES_USER=KyooUser
      - POSTGRES_PASSWORD=KyooPassword
      - POSTGRES_DB=kyooDB
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
    depends_on:
      back:
        condition: service_healthy
    volumes:
      - /share/disque12TB/films/to-re-download:/video:ro
      - /tmp/kyoo_cache:/cache
      - metadata:/metadata
    devices:
      - /dev/dri:/dev/dri

  traefik:
    image: traefik:v3.2
    restart: unless-stopped
    command:
      - "--ping=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entryPoints.web.address=:8901"
      - "--accesslog=true"
    depends_on:
      back:
        condition: service_healthy
    ports:
      - "8901:8901"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    healthcheck:
      test: ["CMD", "traefik", "healthcheck", "--ping"]
      interval: 10s
      timeout: 2s
      retries: 20
      start_period: 5s

  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      - MEILI_ENV=production
      - POSTGRES_USER=KyooUser
      - POSTGRES_PASSWORD=KyooPassword
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
    volumes:
      - db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U KyooUser -d kyooDB"]
      interval: 5s
      timeout: 5s
      retries: 20

  meilisearch:
    image: getmeili/meilisearch:v1.4
    restart: unless-stopped
    volumes:
      - search:/meili_data
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_MASTER_KEY=ghvjkgisbgkbgskegblfqbgjkebbhgwkjfb
      - MEILI_ENV=production
    depends_on:
      migrations:
        condition: service_completed_successfully
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://meilisearch:7700/health"]
      interval: 30s
      timeout: 5s
      retries: 20

  rabbitmq:
    image: rabbitmq:4-alpine
    restart: unless-stopped
    environment:
      - RABBITMQ_DEFAULT_USER=kyoo
      - RABBITMQ_DEFAULT_PASS=aohohunuhouhuhhoahothonseuhaoensuthoaentsuhha
    depends_on:
      meilisearch:
        condition: service_healthy
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 10s

volumes:
  kyoo:
  db:
  metadata:
  search:
```
